##
##  Agentic Software Engineering (ASE)
##  Copyright (c) 2025-2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under GPL 3.0 <https://spdx.org/licenses/GPL-3.0-only>
##

all: \
    ase-all-in-one \
    ase-code-analyze \
    ase-code-craft \
    ase-task-edit \
    ase-task-implement \
    ase-meta-evaluate \
    ase-arch-discover \
    ase-meta-persona \
    ase-meta-diaboli

ase-all-in-one:
	bash render.bash ase-all-in-one
ase-code-analyze:
	bash render.bash ase-code-analyze
ase-code-craft:
	bash render.bash ase-code-craft
ase-task-edit:
	bash render.bash ase-task-edit
ase-task-implement:
	bash render.bash ase-task-implement
ase-meta-evaluate:
	bash render.bash ase-meta-evaluate
ase-arch-discover:
	bash render.bash ase-arch-discover
ase-meta-persona:
	bash render.bash ase-meta-persona
ase-meta-diaboli:
	bash render.bash ase-meta-diaboli

clean:
	-rm -f *.gif *.mp4 *.tape

